### ISSUE TITLE
Is this supporting also ODM documents?

### ISSUE THREAD

**Issue by PeterLabos** [Prezent/doctrine-translatable#32]
I just looked at the code, ad everywhere is used Doctrine ORM. That I like to confirm, if it was at least tried with ODM, or if it is planned to support ODM.

**Comment by sandermarechal** [comment]
This library only support Doctrine ORM at the moment. It has not been tested or developed with ODM in mind.

It doesn't really make sense to use this library with ODM. Because of the tree-like structure of ODM documents you can easily store translations inside an ODM document already. This is not possible in ORM because ORM runs on a relational database, hence this library.

**Comment by PeterLabos** [comment]
Thank you for answer and direction. When I started to use ODM more, I realised that translations are better to store in Document directly.
